# Generated by Django 4.2.11 on 2026-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUBADMIN', 'Sub-Administrador'), ('DOCENTE', 'Docente'), ('BIOMETRICO', 'Biométrico')], max_length=20, unique=True),
        ),
    ]
