# Generated by Django 4.2.11 on 2026-03-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_dui_alter_user_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincontingency',
            name='pin_index',
            field=models.CharField(blank=True, db_index=True, help_text='Fast lookup hash (SHA256)', max_length=64, null=True),
        ),
    ]
