# Generated by Django 4.2.11 on 2026-03-22 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, help_text='Ubicación física o notas adicionales', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(default='Raspberry Pi 4 Model B', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Número de serie único del hardware', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Nombre amigable del dispositivo (ej. RPi-Laboratorio-1)', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la cerradura (ej. Puerta Principal)', max_length=100)),
                ('gpio_pin', models.IntegerField(help_text='PIN GPIO donde está conectado el servomotor (ej. 18)')),
                ('lock_type', models.CharField(choices=[('SERVO', 'Servomotor'), ('MAGNETIC', 'Cerradura Electromagnética'), ('SOLENOID', 'Solenoide')], default='SERVO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='access.aula')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='devices.device')),
            ],
            options={
                'verbose_name': 'Cerradura',
                'verbose_name_plural': 'Cerraduras',
                'db_table': 'device_locks',
            },
        ),
    ]
