# Generated by Django 4.2.11 on 2026-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_description_device_model_device_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='open_duration',
            field=models.IntegerField(default=5, help_text='Duración en segundos que la puerta permanece abierta (ej. 5)'),
        ),
    ]
