# Generated by Django 4.2.11 on 2026-03-19 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_id', models.CharField(help_text='Azure AI Face Person ID (returned after enrollment).', max_length=255)),
                ('storage_url', models.URLField(help_text='Azure Blob Storage URL of the enrolled face image.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is the active enrollment for recognition.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user this biometric record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='biometrics', to='users.user')),
            ],
            options={
                'verbose_name': 'Biométrico',
                'verbose_name_plural': 'Biométricos',
                'db_table': 'biometrics',
                'ordering': ['-updated_at'],
            },
        ),
    ]
