# Generated by Django 4.2.11 on 2026-03-19 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('desired_state', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='CLOSED', max_length=10)),
                ('actual_state', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='CLOSED', max_length=10)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aulas',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='access.aula')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='access.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='users.user')),
            ],
            options={
                'verbose_name': 'Permiso de Acceso',
                'verbose_name_plural': 'Permisos de Acceso',
                'db_table': 'access_permissions',
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(choices=[('FACE', 'Reconocimiento Facial'), ('PIN', 'PIN de Contingencia'), ('MANUAL', 'Manual')], max_length=10)),
                ('result', models.CharField(choices=[('SUCCESS', 'Acceso Concedido'), ('DENIED', 'Acceso Denegado')], max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Denial reason or additional context.', null=True)),
                ('alert_flag', models.BooleanField(default=False, help_text='Flagged by service layer for anomalous or suspicious events.')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Correlates events across device and backend for distributed tracing.')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='access.aula')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='devices.device')),
                ('user', models.ForeignKey(blank=True, help_text='Null if user could not be identified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='users.user')),
            ],
            options={
                'verbose_name': 'Evento de Acceso',
                'verbose_name_plural': 'Eventos de Acceso',
                'db_table': 'access_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
