# Generated by Django 4.2.11 on 2026-03-22 19:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_dui_alter_user_fecha_nacimiento_and_more'),
        ('access', '0002_schedule_is_anytime_alter_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='method',
            field=models.CharField(choices=[('FACE', 'Reconocimiento Facial'), ('PIN', 'PIN de Contingencia'), ('OTP', 'Código de Acceso (OTP)'), ('MANUAL', 'Manual')], max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_otps', to='users.user')),
            ],
            options={
                'verbose_name': 'OTP de Docente',
                'verbose_name_plural': 'OTPs de Docentes',
                'db_table': 'teacher_otps',
                'ordering': ['-created_at'],
            },
        ),
    ]
