# Generated by Django 4.2.11 on 2026-03-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_accessevent_method_teacherotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Time taken to process the request in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='score',
            field=models.FloatField(blank=True, help_text='Biometric similarity score (if applicable).', null=True),
        ),
    ]
