# Generated by Django 4.2.11 on 2026-03-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_description_device_model_device_serial_number_and_more'),
        ('access', '0003_alter_accessevent_method_teacherotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='alert_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='is_false_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='validation_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='access.aula'),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='devices.device'),
        ),
    ]
