# Generated by Django 4.2.11 on 2026-03-23 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_accessevent_response_time_accessevent_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
