# Generated by Django 4.2.11 on 2026-03-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_accessevent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='alert_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='is_false_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='validation_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
