# Generated by Django 4.2.11 on 2026-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_accessevent_alert_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, help_text='Fecha específica para horarios no recurrentes.', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Si es True, se repite todas las semanas según el día. Si es False, solo aplica en la fecha específica.'),
        ),
    ]
