# Generated by Django 4.2.11 on 2026-03-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_accessevent_alert_reviewed_and_more'),
        ('access', '0007_schedule_date_schedule_is_recurring'),
    ]

    operations = [
    ]
