# Generated by Django 4.2.11 on 2026-03-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_merge_20260323_2153'),
        ('access', '0008_merge_20260323_2158'),
    ]

    operations = [
    ]
